from . import oeh_medical_patient
from . import oeh_medical_ethnic_groups
from . import oeh_medical_pathology
from . import oeh_medical_genetics
from . import oeh_medical_insurance
from . import oeh_medical_medicaments
from . import oeh_icd10pcs
from . import oeh_medical_lifestyle
from . import oeh_medical_imaging
from . import oeh_medical_lab
from . import oeh_medical_whatsapp_config
from . import oeh_medical_surgery
from . import oeh_medical_pediatrics_newborn
from . import oeh_medical_pediatrics_psc
from . import oeh_medical_pediatrics_growth_chart_who