services:
  postgres:
    image: postgres:15
    container_name: odoo17_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo17
      POSTGRES_PASSWORD: odoo17
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    build: .
    container_name: odoo17_app
    depends_on:
      - postgres
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo17.conf:/etc/odoo/odoo.conf
      - //var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    user: root    # <-- clave: arrancar como root
    command: >
      bash -c "chmod 666 /var/run/docker.sock &&
               su odoo -s /bin/bash -c 'odoo -c /etc/odoo/odoo.conf --limit-time-real=600 --limit-time-cpu=600'"

volumes:
  postgres-data:
  odoo-data: