[options]
db_host = postgres
db_port = 5432
db_user = odoo17
db_password = odoo17
db_name = odoo17_db
addons_path = /mnt/extra-addons/oehealth_original,/mnt/extra-addons/oehealth_extensiones,/mnt/extra-addons/oehealth_mis_extensiones,/mnt/extra-addons/portal_saas,/usr/lib/python3/dist-packages/odoo/addons
# Comenta o cambia la ruta del logfile:
# logfile = /var/log/odoo/odoo.log
logfile = False  # Esto envía los logs a stdout (consola)
log_level = info
dev_mode = reload,xml
list_db = True
dbfilter = .*
admin_passwd = adolfomr1107